# Generated by Django 4.2.7 on 2023-11-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dueDate', models.DateField()),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enrollmentCapacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploadDate', models.DateField()),
                ('documentType', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.course')),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dateJoined', models.DateField()),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Administrator')], max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('submissionContent', models.TextField()),
                ('submissionDate', models.DateField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user')),
            ],
            options={
                'db_table': 'Submission',
            },
        ),
        migrations.CreateModel(
            name='ReadingState',
            fields=[
                ('readingStateId', models.AutoField(primary_key=True, serialize=False)),
                ('readState', models.IntegerField()),
                ('lastReadDate', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user')),
            ],
            options={
                'db_table': 'ReadingState',
            },
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('interactionId', models.AutoField(primary_key=True, serialize=False)),
                ('interactionType', models.CharField(max_length=50)),
                ('interactionDate', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user')),
            ],
            options={
                'db_table': 'InteractionHistory',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeId', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user')),
            ],
            options={
                'db_table': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('enrollmentDate', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user')),
            ],
            options={
                'db_table': 'Enrollment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALEMNIap.course'),
        ),
    ]
